name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '🚨 Break Change'
    label: 'BREAKING CHANGE'
change-template: '* $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: 'New Release'
replacers:
  - search: '/.+:\s?/g'
    replace: '* '
  - search: ' @github-actions'
    replace: ''
sort-by: 'title'
sort-direction: 'ascending'
version-resolver:
  major:
    labels:
      - 'BREAKING CHANGE'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bugfix'
      - 'fix'
      - 'chore'
      - 'cicd'
  default: patch
exclude-labels:
  - 'skip-changelog'
  - 'ignore'
template: |
  ## Changelog
  $CHANGES