name = "cf-yasser-blog-preview"
main = "dist/index.js"
compatibility_date = "2022-07-12"
workers_dev = true

[env.production]
send_metrics=true

[env.preview]
send_metrics=false

[observability]
enabled = true