name: Build & Deploy

on:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
env:
  node_version: 24
  APP_NAME: yasser-blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2
      - name: set cache key
        id: cache_key
        shell: bash
        run: echo "cached_key=build-output" >> "$GITHUB_OUTPUT"
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5   # this will put output as environment variable
      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false
          version: 10
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile
      - name: build the app
        shell: bash
        run: pnpm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.cache_key.outputs.cached_key }}
          path: ./dist
    outputs:
      cache-key: ${{ steps.cache_key.outputs.cached_key }}
  test:
    runs-on: ubuntu-latest
    needs: build
    if: false
    name: test
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Clean pnpm cache
        shell: bash
        run: pnpm cache clean --force
      - name: Install dependencies
        shell: bash
        run: pnpm ci --prefer-offline --no-audit
      - name: Run unit tests
        shell: bash
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
          CI: true
        run: pnpm run test -- --code-coverage
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name != github.event.repository.default_branch
    permissions:
      contents: read
      deployments: write
    name: deploy
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false
          version: 10
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build.outputs.cache-key }}
          path: ./dist
      - name: update wrangler.toml
        run: |
          sed -i 's/name = ".*"/name = "${{ env.APP_NAME }}-pr-${{ github.event.pull_request.number }}"/g' wrangler.preview.toml
          mv wrangler.preview.toml wrangler.toml
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        id: deploy
        env:
          KEY: VALUE
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          packageManager: pnpm
          command: |
            pages deploy dist
          vars: |
            KEY
      - name: print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
      - uses: altinukshini/deployment-action@master
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          pr: true
          pr_id: ${{ github.event.pull_request.number }}
          target_url: ${{ steps.deploy.outputs.deployment-url }}
          ref: ${{ github.event.pull_request.head.ref }}
          environment: preview
          initial_status: success