name: CF worker destroy
on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'Pull Request number to delete its deployment'
        required: true
  pull_request:
    types:
    - closed
jobs:
  delete:
    runs-on: ubuntu-latest
    name: Delete CF Worker Deployment
    env:
      APP_NAME: yasser-blog
    steps:
      - name: Delete worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: |
            delete --name "${{ env.APP_NAME }}-pr-${{ github.event.pull_request.number || github.event.number }}"
