name: Weekly cleaner
on:
  schedule:
    - cron: "0 21 * * 1"
  workflow_dispatch:

jobs:
  clean:
    name: Delete all caches
    runs-on: ubuntu-20.04
    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: 'false'
          github-token: ${{ github.token }}
      - name: Clear Artifact
        uses: geekyeggo/delete-artifact@v6
        with:
          name: build-output